[tool.poetry]
name = "luxafaret"
version = "1.1.0"
description = "ğŸğŸ‘ğŸ–ğŸ¨ğŸŒˆ LuxafÃ¥ret - colourize your Luxafor flag from Python"
authors = ["Simon LundstrÃ¶m <github-commits@soy.se>"]
license = "ISC"

[tool.poetry.dependencies]
hidapi = "~=0.7.99.post21"
webcolors = "~=1.10"

[tool.poetry.dev-dependencies]
black = "~=19.10b0"
isort = "~=4.3.21"
pylint = "~=2.3.1"

[tool.poetry.scripts]
luxafaret = 'luxafaret:main'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
